projects:
  FAST AppSync API:
    schemaPath: graphql/schema.json
    includes:
      - graphql/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        graphQLApiId: nuerz7qsw5cm7cjme4odwmesdy
        codeGenTarget: swift
        generatedFileName: amplify/API.swift
        docsFilePath: graphql
        region: us-east-1
      endpoints:
        prod: >-
          https://klchv4y3efga5i6dydzloxaule.appsync-api.us-east-1.amazonaws.com/graphql
